name: Docker Image CI

on:
  push:
  schedule:
    - cron:  '0 10 1 * *'

jobs:
  github:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        if: success()
        run: docker build -t vaple/phpcodesniffer:latest -t vaple/phpcodesniffer:`date +%y.%m` .
        
      - name: Push to docker hub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push vaple/phpcodesniffer:latest
          args: push vaple/phpcodesniffer:`date +%y.%m`
