name: Docker Image CI

on: [push]

jobs:
  github:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#          DOCKER_REGISTRY_URL: docker.pkg.github.com

      - name: Build image
        if: success()
        run: docker build . --file Dockerfile --tag vaple/phpcodesniffer:latest --tag vaple/phpcodesniffer:(date +%y.%m)
#        run: docker build -t docker.pkg.github.com/${{ github.repository }}/app:latest .
        
      - name: Push to docker hub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push docker.pkg.github.com/${{ github.repository }}:latest

#jobs:
#
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag vaple/phpcodesniffer:$(date +%y.%m)
