name: Docker Image CI

on:
  push:
  schedule:
    - cron:  '0 10 1 * *'

jobs:
  build_image:
    runs-on: ubuntu-latest    
    steps:

      - uses: actions/checkout@v2

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REPO: vaple/phpcodesniffer

      - name: Build image
        if: success()
        run: docker build -t ${ REPO }:latest -t vaple/phpcodesniffer:`date +%y.%m` .
        
      - name: Push to docker hub :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push vaple/phpcodesniffer:latest

      - name: Push to docker hub :tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push vaple/phpcodesniffer:`date +%y.%m`
        
      - uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.chat }} # user id or channel name secret
          token: ${{ secrets.token }} # token secret
          status: ${{ job.status }} # do not modify this line
